
     do $system.OBJ.ImportDir("/opt/FHIRReportGeneration/src/FhirReportGeneration/",,"cbrpsuy",,1)
     Set tSC = $ClassMethod("EnsPortal.AutoStartProduction","ApplyID","FhirReportGeneration.Productionn",0)
     Do ##class(FhirReportGeneration.fhirserver.Util).SetupServer()
     Do ##class(FhirReportGeneration.fhirserver.Util).update()
     zn "%SYS"
     
     
     Do ##class(Security.Users).UnExpireUserPasswords("*")

     
     halt
